# Generated by Django 3.2.18 on 2023-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_album_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
