# Generated by Django 3.2.18 on 2023-04-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_album_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
