# Generated by Django 3.2.18 on 2023-04-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_album_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='ratings',
        ),
        migrations.AddField(
            model_name='album',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Burn it'), (2, '2 - Mute'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - OK'), (6, '6 - Listenable'), (7, '7 - Good'), (8, '8 - Recommended'), (9, '9 - Perfect'), (10, '10 - Master Piece')], default=7),
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'HipPop'), (2, 'RnB')], default=1),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
