# Generated by Django 3.2.18 on 2023-04-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='album',
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
