# Generated by Django 3.2.18 on 2023-04-30 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_album_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
