# Generated by Django 3.2.18 on 2023-04-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_artist_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='content',
            new_name='piece',
        ),
    ]
