# Generated by Django 3.2.18 on 2023-04-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_content_artist_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.CharField(choices=[('1', '1 - Burn it'), ('2', '2 - Mute'), ('3', '3 - Terrible'), ('4', '4 - Bad'), ('5', '5 - OK'), ('6', '6 - Listenable'), ('7', '7 - Good'), ('8', '8 - Recommended'), ('9', '9 - Perfect'), ('10', '10 - Master Piece')], default='7', max_length=6),
        ),
    ]
